-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM(SELECT SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
    FROM ONLINE_SALE
    UNION
    SELECT SALES_DATE,PRODUCT_ID,NULL,SALES_AMOUNT
    FROM OFFLINE_SALE) A
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE)  = '3'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID